name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # Updates every 12 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: prem-x
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "dist/*.svg"


